# Generated by Django 3.1 on 2021-01-05 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('father_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=11, null=True)),
                ('address_lane1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_lane2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_lane3', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('adharcard_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document1', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='documents')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
