# Generated by Django 3.1 on 2021-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('T', 'Table'), ('M', 'Manager'), ('C', 'Chef'), ('W', 'Waiter')], max_length=50, null=True),
        ),
    ]
