# Generated by Django 3.1 on 2021-02-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210222_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('Table', 'Table'), ('Manager', 'Manager'), ('Chef', 'Chef'), ('Waiter', 'Waiter')], max_length=50, null=True),
        ),
    ]
