# Generated by Django 3.1 on 2021-04-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='approx_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
