# Generated by Django 3.1 on 2021-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, default='Not Done', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
